
# deployment 
apiVersion: apps/v1

kind: Deployment
metadata:
    name: event-bus
spec:
    replicas: 1
    selector:
        matchLabels:
            app: event-bus
    template:
        metadata:
            labels:
                app: event-bus
        spec:
            containers:
                - name: event-bus
                  image: sidnaseem/event-bus:latest
    


---
# NodePort for access it outside of cluster

apiVersion: v1

kind: Service

metadata:
    name : event-bus-nodePort
spec:
    type: NodePort
    selector:
        app: event-bus
    ports:
        - name: event-bus-nodePort-srv
          protocol: TCP
          port: 3010
          targetPort: 3010



---
# cluster_ip access other pods inside k8s cluster


apiVersion: v1

kind: Service

metadata:
    name: event-bus-clus-ip
spec:
    type: ClusterIP
    selector:
        app: event-bus
    ports:
        - name: event-bus-clus-ip-srv
          protocol: TCP
          port: 3010
          targetPort: 3010

